# Generated by Django 5.2.13 on 2026-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_author_alter_book_genre_alter_book_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
