# Generated by Django 5.2.13 on 2026-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="embedding",
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=4.0),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_book_title"
            ),
        ),
    ]
