# Generated by Django 5.2.13 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_embedding_alter_book_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
